---
 tasks file for wp-dependencies
- name: Update packages (this is equivalent to yum update -y)
  yum: name=* state=latest
- name: Install dependencies for WordPress
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - mysql-server
    - php5-mysql
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - python-mysqldb
